import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rafał Zając",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <NavBar />
        <main className="mt-[55px] min-h-screen bg-gradient-to-b from-blue-950 to-sky-950 p-3 text-justify text-slate-100 lg:mt-0">
          {children}
        </main>
      </body>
    </html>
  );
}
