"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";
import { MouseEvent } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Rafał Zając",
//   description: "Generated by create next app",
// };

const cursorStyle = (e: MouseEvent<HTMLBodyElement>) => {
  let cursor = document.querySelector("#cursor") as HTMLElement;
  cursor.style.top = e.pageY + "px";
  cursor.style.left = e.pageX + "px";
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className} onMouseMove={cursorStyle}>
        <div id="cursor"></div>
        <NavBar />
        <main className="mt-[55px] min-h-screen bg-gradient-to-r from-blue-950 to-sky-950 p-3 text-justify text-slate-100 ">
          {children}
        </main>
      </body>
    </html>
  );
}
